<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Get In Touch_submit-contact-form</name>
   <tag></tag>
   <elementGuidId>663469e2-39a9-4057-9910-3035858032d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#submit-contact-form</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='submit-contact-form']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7b55f233-5583-4cdb-9848-1e94927366a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>faa797a4-2242-4eca-a9a6-3c48b62d0456</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary w-75</value>
      <webElementGuid>9fe81740-7e39-4536-8a57-b5ff2206d211</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>submit-contact-form</value>
      <webElementGuid>f5bd40f1-956a-431e-bf33-416bee7872ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Send Message</value>
      <webElementGuid>8680b6f1-059e-46ca-bb10-dba7c983a53a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-dismiss</name>
      <type>Main</type>
      <value>toast</value>
      <webElementGuid>7989e3a9-b640-4ed1-95ec-4fd3aa9124fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Close</value>
      <webElementGuid>8c9415a4-c38a-46c5-991e-628594992ece</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;submit-contact-form&quot;)</value>
      <webElementGuid>bc8595b5-f83c-4a1e-8ada-f75ccac8479e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='submit-contact-form']</value>
      <webElementGuid>861e70a6-b3ef-442b-bbf6-cca34c5462bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contact-form']/form/div/input</value>
      <webElementGuid>11b78262-0690-4339-8bd1-ce68391fd81c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/input</value>
      <webElementGuid>68c732c2-7d31-4e33-adec-5963b4fc14b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @id = 'submit-contact-form']</value>
      <webElementGuid>e485d664-0322-44cc-81e8-17d4bb0de5a3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
